In [1]:
from ultralytics import YOLO
import cv2
from PIL import Image
import os

In [2]:
Per_model = YOLO("../../data_20/runs/detect/fashion-v12/weights/best.pt")

In [3]:
model = Per_model

In [4]:
names = model.names
names

{0: 'Casual_Jeans',
 1: 'Casual_Sneakers',
 2: 'Casual_Top',
 3: 'Corporate_Gown',
 4: 'Corporate_Shoe',
 5: 'Corporate_Skirt',
 6: 'Corporate_Top',
 7: 'Corporate_Trouser',
 8: 'Native',
 9: 'Shorts',
 10: 'Suits',
 11: 'Tie'}

In [5]:
conf_threshold = 0.6

In [6]:
output_dir = "../video_crops"
os.makedirs(output_dir, exist_ok=True)

In [7]:
video_path = "../data/videos/2025-05-31_14-01-37_UTC.mp4"
cap = cv2.VideoCapture(video_path)



In [8]:
frame_count = 0

In [9]:
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    pil_image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    results = model(frame)[0]
    print(results.boxes)  # Print raw output
    print(results.boxes.xyxy)  # Bounding boxes
    print(results.boxes.conf)  # Confidence scores
    print(results.boxes.cls)   # Class indices

    for i, (box, conf, cls) in enumerate(zip(results.boxes.xyxy, results.boxes.conf, results.boxes.cls)):
        if conf < conf_threshold:
            continue
        x1, y1, x2, y2 = map(int, box)
        cropped = pil_image.crop((x1, y1, x2, y2))
        class_id = int(cls.item())
        class_name = names[class_id]
        crop_filename = f"{output_dir}/frame{frame_count}_obj{i}_{class_name}_conf{conf:.2f}.jpg"
        cropped.save(crop_filename)
        print(f"Saved: {crop_filename}")

    frame_count += 1

cap.release()
cv2.destroyAllWindows()


0: 640x384 1 Corporate_Gown, 167.8ms
Speed: 13.4ms preprocess, 167.8ms inference, 437.1ms postprocess per image at shape (1, 3, 640, 384)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([3.], device='cuda:0')
conf: tensor([0.4344], device='cuda:0')
data: tensor([[2.2222e+02, 4.2063e+02, 6.2622e+02, 1.2783e+03, 4.3443e-01, 3.0000e+00]], device='cuda:0')
id: None
is_track: False
orig_shape: (1280, 720)
shape: torch.Size([1, 6])
xywh: tensor([[424.2194, 849.4574, 404.0028, 857.6545]], device='cuda:0')
xywhn: tensor([[0.5892, 0.6636, 0.5611, 0.6700]], device='cuda:0')
xyxy: tensor([[ 222.2180,  420.6301,  626.2208, 1278.2847]], device='cuda:0')
xyxyn: tensor([[0.3086, 0.3286, 0.8698, 0.9987]], device='cuda:0')
tensor([[ 222.2180,  420.6301,  626.2208, 1278.2847]], device='cuda:0')
tensor([0.4344], device='cuda:0')
tensor([3.], device='cuda:0')

0: 640x384 1 Corporate_Gown, 17.3ms
Speed: 2.9ms preprocess, 17.3ms inference, 6.5ms postprocess per image at shape (1, 3, 6

In [ ]:
video_path = "C:/Users/isatyamks/Repositories/Stealth/flickd/data/videos/2025-05-31_14-01-37_UTC.mp4"
cap = cv2.VideoCapture(video_path)

if not cap.isOpened():

    print(f"[!] Failed to open video at: {video_path}")
    return


SyntaxError: 'return' outside function (939573985.py, line 6)

In [5]:
import os

video_path = "../data/videos/2025-05-31_14-01-37_UTC.mp4"
abs_path = os.path.abspath(video_path)

print("Resolved path:", abs_path)
print("File exists:", os.path.exists(video_path))


Resolved path: c:\Users\isatyamks\Repositories\Stealth\flickd\data\videos\2025-05-31_14-01-37_UTC.mp4
File exists: True
